### ISSUE TITLE
CAP-SMD_L3.2-W1.6 What part?

### ISSUE THREAD

**Issue by TheBekker** [Dave19171/split-flap#3]
Can you help specifying the "CAP-SMD_L3.2-W1.6" part?

![image](https://user-images.githubusercontent.com/3404996/126009816-39db3750-4181-459e-bf91-d352d692692a.png)

**Comment by Dave19171** [comment]
Are you aware, that you need only one PCB with all the parts? Read the instructions on page 7 for details. There is also a table with each part on page 5.

I used this capacitor originally: https://lcsc.com/product-detail/Tantalum-Capacitors_TORCH-CA45-A-10V-22%CE%BCF-K_C503893.html
It does not seem to be in stock anymore.
The data sheet for the AMS1117-3.3 says: "The circuit design used in the AMS1117 series requires the use of
an output capacitor as part of the device frequency compensation. The addition of 22µF solid tantalum on the output will ensure
stability for all operating conditions. "

Since you only need one, I suggest you get one elsewhere and solder it yourself.  You need a 
22uF >5V tantalum capacitor in 0805 size.

**Comment by TheBekker** [comment]
Ahh i just saw that the instructions are only on PrusaPrinters :) 
Bit confusing that half is here and other ther :)

I'll check the instructions, thanks!

**Comment by Dave19171** [comment]
Just the instructions for the code on here. Everything electromechanical is on prusaprinters.
